### ISSUE TITLE
Executed the code but the error pops up.

### ISSUE THREAD

**Issue by LokeshPullagura** [JordiCorbilla/mpi4py-examples#1]
When i executed the code, I got the error as stated below:

Traceback (most recent call last):
  File "MPI_Multiplication.py", line 75, in <module>
    row = a[offset, :]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Can anyone help me in solving this issue?

Thanks in advance.

**Comment by mymindd** [comment]
in line 53 should cast result of divided to integer, as below
```
else:
    slice = int(numberRows / (worldSize-1))
```

**Comment by LokeshPullagura** [comment]
@mymindd As suggested, I have changed in the code, however another error pops up as below:

Traceback (most recent call last):
  File "/home/lokesh/PycharmProjects/mpi/MPI_Multiplication.py", line 118, in <module>
    comm.Recv([res1, MPI.FLOAT], source=1, tag=1)
  File "mpi4py/MPI/Comm.pyx", line 285, in mpi4py.MPI.Comm.Recv
mpi4py.MPI.Exception: Invalid rank, error stack:
PMPI_Recv(171): MPI_Recv(buf=0x1a5a800, count=20000, MPI_FLOAT, src=1, tag=1, MPI_COMM_WORLD, status=0x1) failed
PMPI_Recv(108): Invalid rank has value 1 but must be nonnegative and less than 1

Can you help me in this?
